MainBundle\Entity\Abonnement:
    type: entity
    table: abonnement
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idAbo:
            type: integer
            nullable: false
            unsigned: false
            column: id_abo
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
        resum:
            type: string
            nullable: false
            length: 255
            fixed: false
        prix:
            type: integer
            nullable: false
            unsigned: false
        dureeAbo:
            type: datetime
            nullable: false
            column: duree_abo
    lifecycleCallbacks: {  }
