MainBundle\Entity\Distrib:
    type: entity
    table: distrib
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idDistrib:
            type: integer
            nullable: false
            unsigned: false
            column: id_distrib
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
        telephone:
            type: string
            nullable: false
            length: 255
            fixed: false
        adresse:
            type: string
            nullable: true
            length: 255
            fixed: false
        cpostal:
            type: string
            nullable: true
            length: 255
            fixed: false
        ville:
            type: string
            nullable: true
            length: 255
            fixed: false
        pays:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
