MainBundle\Entity\Employee:
    type: entity
    table: null
    repositoryClass: MainBundle\Repository\EmployeeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
