MainBundle\Entity\FichePersonne:
    type: entity
    table: fiche_personne
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idPerso:
            type: integer
            nullable: false
            unsigned: false
            column: id_perso
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
        prenom:
            type: string
            nullable: false
            length: 255
            fixed: false
        dateNaissance:
            type: datetime
            nullable: false
            column: date_naissance
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
        adresse:
            type: string
            nullable: true
            length: 255
            fixed: false
        cpostal:
            type: string
            nullable: false
            length: 255
            fixed: false
        ville:
            type: string
            nullable: false
            length: 255
            fixed: false
        pays:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
