MainBundle\Entity\Film:
    type: entity
    table: film
    manyToOne:
        genre:
            targetEntity: Genre
            joinColumn:
                name: id_genre
                referencedColumnName: id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: AUTO
    fields:
        idGenre:
            type: boolean
            nullable: true
            column: id_genre
        idDistrib:
            type: integer
            nullable: true
            unsigned: false
            column: id_distrib
        titre:
            type: string
            nullable: false
            length: 255
            fixed: false
        resum:
            type: string
            nullable: true
            length: 255
            fixed: false
        dateDebutAffiche:
            type: date
            nullable: true
            column: date_debut_affiche
        dateFinAffiche:
            type: date
            nullable: true
            column: date_fin_affiche
        dureeMin:
            type: integer
            nullable: true
            unsigned: false
            column: duree_min
        anneeProd:
            type: integer
            nullable: true
            unsigned: false
            column: annee_prod
    lifecycleCallbacks: {  }
