MainBundle\Entity\Genre:
    type: entity
    table: genre
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
