MainBundle\Entity\Genre:
    type: entity
    table: genre
    manyToOne:
        film:
            targetEntity: Film
            inversedBy: genres
    id:
        id:
            type: boolean
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
