MainBundle\Entity\Reduction:
    type: entity
    table: reduction
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
        dateDebut:
            type: datetime
            nullable: false
            column: date_debut
        dateFin:
            type: datetime
            nullable: false
            column: date_fin
        pourcentageReduc:
            type: integer
            nullable: false
            unsigned: false
            column: pourcentage_reduc
    lifecycleCallbacks: {  }
