film_index:
    path:     /
    defaults: { _controller: "MainBundle:Film:index" }
    methods:  GET

film_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:Film:show" }
    methods:  GET



